import React from 'react'
import { Page, Text, View } from '@react-pdf/renderer'
import { ReportOptions } from '@/lib/services/pdfReportService'
import { styles, formatDate } from '@/lib/services/pdfStyles'

interface CoverPageProps {
  options: ReportOptions
  timestamp: string
}

export const CoverPage: React.FC<CoverPageProps> = ({ options, timestamp }) => {
  const getDateRangeText = () => {
    if (options.dateRange?.startDate && options.dateRange?.endDate) {
      return `${formatDate(options.dateRange.startDate)} - ${formatDate(options.dateRange.endDate)}`
    } else if (options.dateRange?.startDate) {
      return `From ${formatDate(options.dateRange.startDate)}`
    } else if (options.dateRange?.endDate) {
      return `Until ${formatDate(options.dateRange.endDate)}`
    }
    return 'All Time'
  }

  return (
    <Page size="A4" style={styles.coverPage}>
      {/* Main Title */}
      <View>
        <Text style={styles.coverTitle}>InCloud Analytics Report</Text>
        <Text style={[styles.coverSubtitle, { marginBottom: 5 }]}>
          J.A's Food Trading
        </Text>
        <Text style={[styles.coverSubtitle, { fontSize: 14, marginBottom: 40 }]}>
          Inventory Management System
        </Text>
      </View>

      {/* Report Details */}
      <View style={{ marginTop: 60, marginBottom: 60 }}>
        <View style={{ marginBottom: 15 }}>
          <Text style={[styles.text, { fontSize: 14, fontWeight: 'bold', textAlign: 'center' }]}>
            Report Period
          </Text>
          <Text style={[styles.coverInfo, { fontSize: 16, marginTop: 5 }]}>
            {getDateRangeText()}
          </Text>
        </View>

        {options.includeAI && (
          <View style={{ marginTop: 20 }}>
            <Text style={[styles.text, { fontSize: 12, textAlign: 'center', color: '#1E40AF' }]}>
              ✓ Includes AI-Powered Insights
            </Text>
          </View>
        )}
      </View>

      {/* Footer Info */}
      <View style={{ position: 'absolute', bottom: 60 }}>
        <Text style={styles.coverInfo}>
          Generated on: {formatDate(timestamp)}
        </Text>
        {options.generatedBy && (
          <Text style={[styles.coverInfo, { marginTop: 5 }]}>
            Generated by: {options.generatedBy}
          </Text>
        )}
        <Text style={[styles.coverInfo, { marginTop: 20, fontSize: 10 }]}>
          CONFIDENTIAL - For Internal Use Only
        </Text>
      </View>
    </Page>
  )
}
